services:

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  financial.api:
    image: ${DOCKER_REGISTRY-}financialapi
    build:
      context: .
      dockerfile: Financial.Api/Dockerfile
    environment:      
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=financial;Username=postgres;Password=postgres
    depends_on:
      db:
        condition: service_healthy
